#!/bin/sh

if [ -z "`getent group named`" ]
then
  /usr/sbin/groupadd -g 25 named
fi

if [ -z "`getent passwd named`" ]
then
  /usr/sbin/useradd  -u 25 -g named -d /var/named -s /bin/false named
  /usr/bin/passwd -l named
fi

/bin/chown root:named  /etc/named.conf
/bin/chown root:named  /var/named
/bin/chown root:named  /var/run/named
/bin/chown root:named  /etc/rndc.conf
/bin/chown root:named  /etc/rndc.key
/bin/chown named:named /var/run/named/named.pid

# End of file
