#!/bin/sh

/usr/bin/gdk-pixbuf-query-loaders --update-cache

# gtk-update-icon-cache comes with gtk, not with gtk3
if [ -x /usr/bin/gtk-update-icon-cache ]; then
	/usr/bin/gtk-update-icon-cache -f -t /usr/share/icons/Trinity
fi

# End of file
